---
- name: Ensure RPM Fusion repos are available
  ansible.builtin.include_role:
    name: repo_rpmfusion

- name: Install Dropbox and Nautilus extension (RPMFusion)
  ansible.builtin.dnf:
    name:
      - dropbox
      - nautilus-dropbox
    state: present
    update_cache: true
  failed_when: false

- name: Try to install Thunderbird via dnf
  ansible.builtin.dnf:
    name: thunderbird
    state: present
  register: desktop_gnome_thunderbird_dnf
  failed_when: false

- name: Install Thunderbird via Flatpak fallback
  community.general.flatpak:
    name: org.mozilla.Thunderbird
    state: present
  when: desktop_gnome_thunderbird_dnf is failed

- name: Install Obsidian and Vorta via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - md.obsidian.Obsidian
    - com.borgbase.Vorta

- name: Ensure psutil is installed
  ansible.builtin.dnf:
    name: python3-psutil
    state: present

- name: Install dotfiles aliases
  become: false
  block:
    - name: Deploy bash aliases
      ansible.builtin.copy:
        src: "{{ role_path }}/files/dotfiles/bash_aliases"
        dest: "{{ target_home }}/.bash_aliases"
        mode: "0644"

    - name: Ensure .bashrc sources aliases
      ansible.builtin.lineinfile:
        path: "{{ target_home }}/.bashrc"
        line: '[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases'
        create: true
        mode: "0644"
        state: present

    - name: Ensure .zshrc sources aliases
      ansible.builtin.lineinfile:
        path: "{{ target_home }}/.zshrc"
        line: '[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases'
        create: true
        mode: "0644"
        state: present

- name: Set GNOME time and calendar properties
  become: false
  become_user: "{{ target_user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_time_and_calendar_properties }}"

- name: Add Ubuntu-like shortcuts
  become: false
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_navigation_shortcuts + gnome_terminal_custom_shortcut }}"

- name: Disable alert sound (terminal 'dingding' noise)
  become : false
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_alert_sound }}"

- name: Enable battery percentage in top bar
  become: false
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_battery_percentage }}"

- name: Enable global dark theme
  become: false
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_dark_theme }}"
