---
gnome_navigation_shortcuts:
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "['<Super>Tab']"

  - key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "['<Shift><Super>Tab']"

  - key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"

  - key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"


gnome_custom_shortcuts:
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

  # Terminal (Ctrl+Alt+T)
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'gnome-terminal'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'gnome-terminal'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Control><Alt>t'"

  # Files (Win+E)
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'files'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'nautilus'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'<Super>e'"

gnome_terminal_custom_shortcut: "{{ gnome_custom_shortcuts }}"

gnome_time_and_calendar_properties:
  - key: "/org/gnome/desktop/calendar/show-weekdate"
    value: true

  - key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

gnome_alert_sound:
  - key: "/org/gnome/desktop/sound/event-sounds"
    value: false

gnome_battery_percentage:
  - key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: true


gnome_mouse_touchpad:
  - key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'flat'"
  
  - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: true


gnome_hot_corner:
  - key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: false

german_us_keyboard_layout:
  - key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'de'), ('xkb', 'us')]"
